# Generated by Django 5.1.3 on 2026-08-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_host_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='allow_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_rename',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='allow_share_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='waiting_room_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
